// This is a file generated by the yeoman generator hapijs

/**
 * Controller which handles requests/responses relating to item
 *
 * @type {itemDao|exports}
 */
var itemDao = require('./item-dao');
var Boom = require('boom');

/**
 * Creates a item
 *
 * @param req
 * @param reply
 */
exports.create = function (req, reply) {

	itemDao.create(req.payload, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/**
 * Gets all items
 *
 * @param req
 * @param reply
 */
exports.find = function (req, reply) {

	itemDao.find(function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/**
 * Get a specific item by id
 *
 * @param req
 * @param reply
 */
exports.findById = function (req, reply) {

	itemDao.findById(req.params.id, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/**
 * Update a specific item by id
 *
 * @param req
 * @param reply
 */
exports.update = function (req, reply) {

	itemDao.update(req.params.id, req.payload, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};
		
/**
 * Remove a specific item by id
 *
 * @param req
 * @param reply
 */
exports.remove = function (req, reply) {

	itemDao.remove(req.params.id, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/* Add new methods above */
