// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets item from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');

/**
 * Creates a item
 *
 * @param payload - The data to be used to create a item
 * @param callback
 */
exports.create = function (payload, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Get's all items
 *
 * @param callback
 */
exports.find = function (callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Get's a specific item by the id
 *
 * @param id  - The id of the item to get
 * @param callback
 */
exports.findById = function (id, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Updates a specific item
 *
 * @param id      - The id of the item to be updated
 * @param payload - The data to be updated
 * @param callback
 */
exports.update = function (id, payload, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/**
 * Remove a specific item
 *
 * @param id      - The id of the item to be deleted
 * @param callback
 */
exports.remove = function (id, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};

/* Add new methods above */