// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to item
 *
 * @type {exports}
 */
var Joi = require('joi');
var itemController = require('./item-ctrl');

module.exports = function() {
  return [
    {
      method: 'POST',
      path: '/items',
      config: {
        description: 'Creates a item',
        handler: itemController.create,
        validate: {
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
		
    {
      method: 'GET',
      path: '/items',
      config : {
        description: 'Fetches all items',
        handler: itemController.find
      }
    },
		
    {
      method: 'GET',
      path: '/items/{id}',
      config : {
        description: 'Fetches a item by id',
        handler: itemController.findById,
        validate: {
          params: {
            id: Joi.number().integer().required()
          }
        }
      }
    },
		
    {
      method: 'PUT',
      path: '/items/{id}',
      config : {
        description: 'Updates a item for a specific id',
        handler: itemController.update,
        validate: {
          params: {
            id: Joi.number().integer().required()
          },
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
		
    {
      method: 'DELETE',
      path: '/items/{id}',
      config : {
        description: 'Remove a item for a specific id',
        handler: itemController.remove,
        validate: {
          params: {
            id: Joi.number().integer().required()
          }
        }
      }
    }
		
		/* Add new methods above */
  ]
}();
